name: Deploy to Codeberg Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
        env:
          # Add your environment variables here
          NODE_ENV: production

      - name: Deploy to Codeberg Pages
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SOURCE_GITHUB_TOKEN }}
        with:
          source-directory: 'public'
          destination-github-username: 'd3d3h3h3'
          destination-repository-name: 'd3d3h3h3.codeberg.page'
          user-email: dd@naymspace.de
          target-branch: main
